### PR TITLE
Add support for adding and removing assignees from issue

### PR DESCRIPTION
**Pull request by soh335**
Hi. 

This pull request contains [add assignees to an issue](https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue), and [remove assignees from an issue](https://developer.github.com/v3/issues/assignees/#remove-assignees-from-an-issue).

Question

* Should I need to add features spec in this p-r? ( I dont know my login name and repository name should not be included in vcr cache response )

### CODE REVIEW

**Comment by piotrmurach** [comment]
Thanks ❤️

**Comment by soh335** [comment]
@piotrmurach would you release it ?

**Comment by piotrmurach** [comment]
@soh335 I should have time to release tomorrow, will let you know.

**Comment by piotrmurach** [comment]
@soh335 Released `v0.18.0` that includes your contributions. Thanks!

**Comment by soh335** [comment]
@piotrmurach thanks you !

**Comment by piotrmurach** [comment]
@soh335 The `v0.18.0` is unfortunately broken but I will release a patch soon! Just received PR that fixes the situation.

**Comment by piotrmurach** [comment]
I've removed the borked `v0.18.0` and released working `v0.18.1`. I've rewritten how files are loaded to prevent magic and be more specific hence the unfortunate breakage. Enjoy!

**Comment by soh335** [comment]
thank you for soon fixing 👍

**Pull request merged**
