### PR TITLE
Upgrade VCR to latest and Webmock to latest

### PR DESCRIPTION
**Pull request by samphilipd**
This is necessary groundwork for tackling #304 

Builds on #303 so merge that first.

### CODE REVIEW

**Comment by piotrmurach** [comment]
I have manually merged this changes due to me messing around with dependencies setup and rerecording some of the feature tests. Do you want me to release a new version with the projects api or do you have time to look into `cards` and `columns` apis as well?

**Comment by samphilipd** [comment]
@piotrmurach I can implement both of those this week.

**Comment by piotrmurach** [comment]
That would be sweet! The only thing I would add is that the smaller the PRs the better, it's much easier to review and merge. 

It should be much smoother to progress now the testing dependencies have been upgraded 😄  I really want to upgrade to `rspec3` and there is a tool that i've been using to slowly convert old specs to new syntax - [transpec](https://github.com/yujinakayama/transpec). If you fancy moving some specs from `spec/client` over to `unit/client` folder for now that would be great.

**Comment by samphilipd** [comment]
@piotrmurach yes I agree about PR size. Now that the tests are sorted it should be pretty straightforward.

I'll see what I can do about the specs.

**Comment by samphilipd** [comment]
@piotrmurach I'd like to use projects to track my progress on the following tasks:

reactions
issues.timeline
migration
orgs.outside_collaborators
orgs.blocking
pull_requests.review_requests
users.gpg_keys
users.blocking
repos.invitations
repos.traffic
repos.community

Any chance you could grant me permissions to create one?

**Pull request closed without merging**
