### PR TITLE
Projects columns

### PR DESCRIPTION
**Pull request by samphilipd**

### CODE REVIEW

**Comment by samphilipd** [comment]
@piotrmurach Should this also have unit specs?

**Comment by piotrmurach** [comment]
I would add unit tests as well, they tend to catch different kind of bugs related to the parsing of arguments etc... 

Another thing that I thought I will do is to add you as collaborator to my `github_api_test` repository which I use for recording cassettes. It's a safe sandbox that I think it would be good for feature tests to us this repo to help with future maintenance.

**Comment by samphilipd** [comment]
@piotrmurach unit tests added.

**Comment by samphilipd** [comment]
@piotrmurach ready for merge

**Comment by piotrmurach** [comment]
Will merge later today.

**Pull request merged**
