### PR TITLE
Add the new Branch Protection API

### PR DESCRIPTION
**Pull request by kartikluke**
Add the new Branch Protection API https://developer.github.com/v3/repos/branches/

### CODE REVIEW

**Comment by kartikluke** [comment]
@piotrmurach Hey according to this blog post https://developer.github.com/changes/2016-06-27-protected-branches-api-update/ I need to add `application/vnd.github.loki-preview+json` to the Accept header to allow me to use the branch protection APIs. I added it in here https://github.com/piotrmurach/github/pull/315/files/e7585ebacf0038173a5313e4d56f7101bb760e3e#diff-b6ad807ef799ca76d23ba7ff1d311795R26 but I'm still getting this error. Can you help me work it out. Once it's working I'll fix up the documentation and tests.

Github::Error::ServiceError: GET https://api.github.com/repos/kartikluke/rails_test/branches/master/protection?access_token=a4a2c1deb8728ac8dab2d1fda7bcbf5e9bf66e0c: 415 - If you would like to help us test the Protected Branches API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.

**Comment by kartikluke** [comment]
@piotrmurach I think adding it to the list doesn't work. Using the accept key works so just need to set the Accept header to `application/vnd.github.loki-preview+json` for `Client::Repos::Branches::Protections`

**Comment by kartikluke** [comment]
@piotrmurach Can you review this. My protections/edit_spec.rb isn't very thorough and I don't know how to write the cucumber specs but I've covered most of the bases.

**Comment by piotrmurach** [comment]
Thanks! ❤️

**Pull request merged**
