### PR TITLE
Add Repo invitations

### PR DESCRIPTION
**Pull request by Siggs2000**
I've added `list` and `delete` functionality for repo collaborator invitations 

No specs yet. I'll try to find some time to do those before this merges, of course. Unless anyone else gets time before I do and wants to jump in! This is working in my own app now though.

### CODE REVIEW

**Comment by Siggs2000** [comment]
@piotrmurach - I've added the specs

**Comment by piotrmurach** [comment]
@Siggs2000 This looks good. However, the tests for listing invitations fail on Travis. Also, would you mind using the `expect(...).to eq(....)` syntax instead of old `....should ==`?

**Comment by Siggs2000** [comment]
@piotrmurach Ill make those syntax changes for sure. I think Travis is is also failing on master though and that is why it’s failing on this PR, isn’t it?

**Comment by piotrmurach** [comment]
@Siggs2000 As far as I can tell it's fine on master, there is only one test failing for `Inviations.list` - [see here](https://travis-ci.org/piotrmurach/github/jobs/618693364?utm_medium=notification&utm_source=github_status)

**Comment by Siggs2000** [comment]
@piotrmurach I fixed that failing spec and updated the syntax and I think it's ok but I'm a little confused about why travis is showing as failed still...

**Comment by piotrmurach** [comment]
Thank you! ❤️

**Pull request merged**
