### PR TITLE
Adds support for new pull request squash merge

### PR DESCRIPTION
**Pull request by codenamev**
This adds support for the [pending additions to the merge API](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button).  Current you have to use a special header to use it (`Accept: application/vnd.github.squirrel-girl-preview`; [reference](https://developer.github.com/changes/2016-05-12-reactions-api-preview/)), but I'd love to get this so we could use it with [git-reflow](https://github.com/reenhanced/gitreflow) :smile:.

* Adds commit_title, commit_message, sha, and squash params to pull_requests.merge
* Bumps ruby version for dev to 2.3.1 (because 2.0.0 is no longer supported :wink:)
* `bundle update hashie, multi_json, oauth2` to fix security issues [reported on gemnasium](https://gemnasium.com/piotrmurach/github)
* Add Ruby 2.3 to travis builds

### CODE REVIEW

**Comment by pboling** [comment]
👍 These are important updates.

**Comment by piotrmurach** [comment]
@codenamev Cheers for the PR I will merge defo this week and release new library - solid promise!
@pboling Point taken, i will handle this and few other PRs this week for sure.

**Comment by codenamev** [comment]
You da man @piotrmurach!  Thanks for an awesome library 😄

**Comment by piotrmurach** [comment]
Hey, just released `v0.14.0` that:
* removes multi_json altogether(this should speed things up as well as make it truly cross ruby solution)
* remove any params checks from pull requests to make it bullet proof for future api changes
* added default preview accept header for merge to make squash work

Let me know if this works for you?

**Pull request merged**
